#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# Makefile for the phy drivers.
#

obj-$(CONFIG_MTK_MIPI_TX) += mtk_mipi_tx.o
obj-$(CONFIG_PHY_MTK_USB_XSPHY)	+= mtk-usb-xsphy.o
obj-$(CONFIG_PHY_MTK_DPRX_PHY)	+= mtk_dprx_phy.o
