#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
subdir-ccflags-$(CONFIG_MTK_DEBUG) += -DDEBUG

obj-$(CONFIG_MTK_CHIPINFO) += chipinfo/
obj-$(CONFIG_MTK_COMPUTERVISION) += computervision/
obj-y += display/
obj-$(CONFIG_MTK_DPRX) += dprx/
obj-y += dsi/
obj-$(CONFIG_MTK_GPU_SUPPORT) += gpu/
obj-$(CONFIG_MTK_IMGPROC) += imgproc/
obj-$(CONFIG_MTK_IVP) += ivp/
obj-$(CONFIG_MTK_LDVT) += ldvt/
obj-$(CONFIG_MTK_MMSYS) += mmsys/
obj-$(CONFIG_MTK_MM_SYSRAM) += mm_sysram/
obj-$(CONFIG_MTK_MUTEX) += mutex/
obj-$(CONFIG_MTK_PMIC_NEW_ARCH) += pmic/
obj-$(CONFIG_MTK_RBFC) += rbfc/
obj-$(CONFIG_MTK_SBRC) += sbrc/
obj-$(CONFIG_MTK_SCP) += scp/
obj-$(CONFIG_MTK_SLICER) += slicer/
obj-$(CONFIG_MTK_TIMESTAMP) += timestamp/
obj-$(CONFIG_MTK_MMSYS_CMMN_TOP) += top/
obj-$(CONFIG_MTK_XTS_SMC) += hal_tsp/
obj-$(CONFIG_MTK_EMI_CTRL) += emi_ctrl/
