obj-$(CONFIG_MTK_LDVT) += vr_tracking/
obj-$(CONFIG_MTK_LDVT) += mtk_common_util.o
obj-$(CONFIG_MTK_CINEMATIC) += cinematic/
obj-$(CONFIG_MTK_DISP_PIPE) += display_pipe/
obj-$(CONFIG_MTK_LDVT) += mm_gaze/
obj-$(CONFIG_MTK_LATENCY) += latency_verify/
