# Core
obj-$(CONFIG_PINCTRL_MTK_COMMON)	+= pinctrl-mtk-common.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_MT3612)		+= pinctrl-mt3612.o
obj-$(CONFIG_PINCTRL_MT3615)		+= pinctrl-mt3615.o
obj-$(CONFIG_PINCTRL_MT8135)		+= pinctrl-mt8135.o
obj-$(CONFIG_PINCTRL_MT8127)		+= pinctrl-mt8127.o
obj-$(CONFIG_PINCTRL_MT8173)		+= pinctrl-mt8173.o
