obj-$(CONFIG_MTK_DISP_PIPE) += mtk_disp_pipe_module.o
mtk_disp_pipe_module-objs := mtk_disp_pipe.o
mtk_disp_pipe_module-objs += mtk_mmsys_test.o
mtk_disp_pipe_module-objs += mtk_lhc_test.o
mtk_disp_pipe_module-objs += mtk_mutex_test.o
obj-$(CONFIG_MTK_DISP_PIPE) += mtk_disp_dev.o
