#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_MTK_DDDS) += mtk_ddds.o
obj-$(CONFIG_MTK_DSI) += mtk_dsi_module.o
mtk_dsi_module-objs := mtk_dsi.o panel_truly_bd0598U40010.o mtk_dsi_debugfs.o
obj-$(CONFIG_MTK_FRMTRK) += mtk_frmtrk.o