#
# Copyright (C) 2018 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_VIDEO_MEDIATEK_IMGSENSOR_V2) += mtk_imgsensor_module.o
mtk_imgsensor_module-objs += kd_sensorlist.o
mtk_imgsensor_module-objs += kd_sensorfunc.o
mtk_imgsensor_module-objs += kd_camera_hw.o
