#dtb-$(CONFIG_ARCH_MEDIATEK) += mt6795-evb.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-evb.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-fpga-basic.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-fpga.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-fpga-camera.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-fpga-ivp.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-fpga-vr-tracking.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-fpga-sie-video.dtb
#dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-emu.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-a0-mini.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-a0-basic.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-a0-release.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-a0-release-nocoresight.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt3612-a0-debug.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
