#
# Copyright (C) 2018 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# Makefile for Mediatek Camera memory driver

mtk-cammem-objs += cammem.o
mtk-cammem-objs += cammem_ion.o
mtk-cammem-objs += cammem_rsvd.o

obj-$(CONFIG_VIDEO_MEDIATEK_CAMERA_MEMORY) += mtk-cammem.o
