snd-soc-mt3611-pcm-objs := \
    mt3611-afe-pcm.o mt3611-afe-util.o mt3611-afe-controls.o mt3611-afe-debug.o mt3611-afe-sysfs.o

snd-soc-mt3611-mach-objs := \
    mt3611-evb.o

obj-$(CONFIG_SND_SOC_MT3611) += snd-soc-mt3611-pcm.o
obj-$(CONFIG_SND_SOC_MT3611_MACH) += snd-soc-mt3611-mach.o
