obj-$(CONFIG_MTK_CMDQ) += mtk-cmdq-helper.o
obj-$(CONFIG_MTK_INFRACFG) += mtk-infracfg.o
obj-$(CONFIG_MTK_PMIC_WRAP) += mtk-pmic-wrap.o
obj-$(CONFIG_MTK_SCPSYS) += mtk-scpsys.o
ifeq ($(CONFIG_MTK_SCPSYS), y)
obj-m += mtk-scpsys-bringup.o
endif
obj-$(CONFIG_MTK_PMICW_P2P) += mtk-pmic-p2p-mt3612.o
obj-$(CONFIG_MTK_DEBUGFS) += mtk-debugfs.o
