obj-$(CONFIG_MTK_CROP) += mtk_crop.o
obj-$(CONFIG_MTK_PADDING) += mtk_padding.o
obj-$(CONFIG_MTK_P2S) += mtk_p2s.o
obj-$(CONFIG_MTK_RSZ) += mtk_resizer.o
obj-$(CONFIG_MTK_WDMA) += mtk_wdma.o
obj-$(CONFIG_MTK_RDMA) += mtk_rdma.o
obj-$(CONFIG_MTK_LHC) += mtk_lhc.o
obj-$(CONFIG_MTK_WARPA) += mtk_warpa.o
