#
# Copyright (C) 2018 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_VIDEO_MEDIATEK_ISP) += isp/
obj-$(CONFIG_VIDEO_MEDIATEK_CCU) += ccu/
obj-$(CONFIG_VIDEO_MEDIATEK_GCE) += gce/
obj-$(CONFIG_VIDEO_MEDIATEK_CAMERA_MEMORY) += cammem/
obj-$(CONFIG_VIDEO_MEDIATEK_IMGSENSOR_V2) += imgsensor/mt3612/
