obj-$(CONFIG_MTD_SPI_NOR)	+= spi-nor.o
obj-$(CONFIG_SPI_FSL_QUADSPI)	+= fsl-quadspi.o
obj-$(CONFIG_MTD_MT81xx_NOR)	+= mtk_quadspi_module.o
mtk_quadspi_module-objs	:= mtk-quadspi.o mtk-partition.o
obj-$(CONFIG_SPI_NXP_SPIFI)	+= nxp-spifi.o
